//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Data.Common;
using NHibernate.Engine;
using NHibernate.SqlCommand;

namespace NHibernate.Multi
{
	using System.Threading.Tasks;
	using System.Threading;

	public partial interface IQueryBatchItem
	{
		
		/// <summary>
		/// Get the commands to execute for getting the not-already cached results of this query.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		/// <returns>The commands for obtaining the results not already cached.</returns>
		Task<IEnumerable<ISqlCommand>> GetCommandsAsync(CancellationToken cancellationToken);

		/// <summary>
		/// Process the result sets generated by <see cref="GetCommands"/>. Advance the results set
		/// to the next query, or to its end if this is the last query.
		/// </summary>
		/// <returns>The number of rows processed.</returns>
		Task<int> ProcessResultsSetAsync(DbDataReader reader, CancellationToken cancellationToken);

		/// <summary>
		/// Process the results of the query, including cached results.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		/// <remarks>Any result from the database must have been previously processed
		/// through <see cref="ProcessResultsSet"/>.</remarks>
		Task ProcessResultsAsync(CancellationToken cancellationToken);

		/// <summary>
		/// Execute immediately the query as a single standalone query. Used in case the data-provider
		/// does not support batches.
		/// </summary>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		Task ExecuteNonBatchedAsync(CancellationToken cancellationToken);
	}
}
