//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NHibernate.Type;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	using System.Threading;
	/// <summary>
	/// TestFixtures for the <see cref="DateTimeType"/>.
	/// </summary>
	[TestFixture]
	public class DateTime2TypeFixtureAsync
	{
		[Test]
		public async Task NextAsync()
		{
			DateTimeType type = NHibernateUtil.DateTime2;
			object current = DateTime.Now.AddMilliseconds(-1);
			object next = await (type.NextAsync(current, null, CancellationToken.None));

			Assert.That(next, Is.TypeOf<DateTime>().And.GreaterThan(current));
		}

		[Test]
		public async Task SeedAsync()
		{
			DateTimeType type = NHibernateUtil.DateTime;
			Assert.IsTrue(await (type.SeedAsync(null, CancellationToken.None)) is DateTime, "seed should be DateTime");
		}
	}
}