//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using NUnit.Framework;

namespace NHibernate.Test.TypesTest
{
	using System.Threading.Tasks;
	/// <summary>
	/// Summary description for StringTypeFixture.
	/// </summary>
	[TestFixture]
	public class StringTypeFixtureAsync : TypeFixtureBase
	{
		protected override string TypeName
		{
			get { return "String"; }
		}

		[Test]
		public async Task InsertNullValueAsync()
		{
			using (ISession s = OpenSession())
			{
				StringClass b = new StringClass();
				b.StringValue = null;
				await (s.SaveAsync(b));
				await (s.FlushAsync());
			}

			using (ISession s = OpenSession())
			{
				StringClass b = (StringClass) await (s.CreateCriteria(
				                              	typeof(StringClass)).UniqueResultAsync());
				Assert.IsNull(b.StringValue);
				await (s.DeleteAsync(b));
				await (s.FlushAsync());
			}
		}
	}
}