// 
// NHibernate.Mapping.Attributes
// This product is under the terms of the GNU Lesser General Public License.
//
//
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
//
//
// This source code was auto-generated by Refly, Version=2.21.1.0 (modified).
//
namespace NHibernate.Mapping.Attributes
{
	
	
	/// <summary>Rule as to how to operate on child objects (for more information, read topics about "persistence by reachability" or "transparent/transitive/cascading persistence")</summary>
	public enum CascadeStyle
	{
		
		/// <summary>Default value (don't use it)</summary>
		Unspecified,
		
		/// <summary>all</summary>
		[System.Xml.Serialization.XmlEnumAttribute("all")]
		All,
		
		/// <summary>all-delete-orphan</summary>
		[System.Xml.Serialization.XmlEnumAttribute("all-delete-orphan")]
		AllDeleteOrphan,
		
		/// <summary>none</summary>
		[System.Xml.Serialization.XmlEnumAttribute("none")]
		None,
		
		/// <summary>save-update</summary>
		[System.Xml.Serialization.XmlEnumAttribute("save-update")]
		SaveUpdate,
		
		/// <summary>delete</summary>
		[System.Xml.Serialization.XmlEnumAttribute("delete")]
		Delete,
		
		/// <summary>delete-orphan</summary>
		[System.Xml.Serialization.XmlEnumAttribute("delete-orphan")]
		DeleteOrphan,
	}
}
