version: '{build}'
image: Visual Studio 2022
skip_branch_with_pr: true
environment:
  matrix:
  - DB: SqlServer2008
    CONNECTION_STRING: Server=(local)\SQL2017;User ID=sa;Password=Password12!;initial catalog=nhibernate;
  - DB: SqlServer2008-MicrosoftDataSqlClientDriver
    CONNECTION_STRING: Server=(local)\SQL2017;User ID=sa;Password=Password12!;initial catalog=nhibernate;TrustServerCertificate=true;
init:
# Required for having windows endlines in sources zip
- git config --global core.autocrlf true
install:
# Install .NET 10, see https://github.com/appveyor/ci/issues/3984 for checking if it remains needed.
# Install script recommended here: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#recommended-version
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Channel 10.0 -InstallDir "$env:ProgramFiles\dotnet"
build: off
before_test:
- ps: |-
    switch ($env:DB) {
      'Odbc' { Start-Service 'MSSQL$SQL2017' }
      'SqlServer2008' { Start-Service 'MSSQL$SQL2017' }
      'SqlServer2008-MicrosoftDataSqlClientDriver' { Start-Service 'MSSQL$SQL2017' }
      'SqlServer2012' { Start-Service 'MSSQL$SQL2017' }
      'SqlServer2012-MicrosoftDataSqlClientDriver' { Start-Service 'MSSQL$SQL2017' }
      'SQLite' { }
    }
test_script:
- cmd: powershell -noprofile -command "& ./build.ps1 -TaskList Set-Configuration,Test -properties @{\"Database\" = \"%DB%\";\"ConnectionString\"=\"%CONNECTION_STRING%\"}"
deploy: off
on_finish:
- ps: |-
    $wc = New-Object 'System.Net.WebClient'
    Get-Item '*-TestResult.xml' | ForEach-Object { 
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", $_)
    }
