//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using NHibernate.DomainModel.NHSpecific;
using NHibernate.DomainModel.Northwind.Entities;
using NHibernate.Driver;
using NHibernate.Exceptions;
using NHibernate.Proxy;
using NHibernate.Type;
using NUnit.Framework;
using static NHibernate.Linq.ExpressionEvaluation;
using NHibernate.Linq;

namespace NHibernate.Test.Linq
{
	using System.Threading.Tasks;
	[TestFixture]
	public class SelectionTestsAsync : LinqTestCase
	{
		[Test]
		public async Task CanGetCountOnQueryWithAnonymousTypeAsync()
		{
			var query = from user in db.Users
						select new { user.Name, RoleName = user.Role.Name };

			int totalCount = await (query.CountAsync());

			Assert.AreEqual(3, totalCount);
		}

		[Test]
		public async Task CanGetFirstWithAnonymousTypeAsync()
		{
			var query = from user in db.Users
						select new { user.Name, RoleName = user.Role.Name };

			var firstUser = await (query.FirstAsync());

			Assert.IsNotNull(firstUser);
		}

		[Test]
		public async Task CanSelectUsingMemberInitExpressionAsync()
		{
			var query = from user in db.Users
						select new UserDto(user.Id, user.Name) { InvalidLoginAttempts = user.InvalidLoginAttempts };

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);
		}

		[Test]
		public async Task CanSelectNestedAnonymousTypeAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							Enums = new
							{
								user.Enum1,
								user.Enum2
							},
							RoleName = user.Role.Name
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedAnonymousTypeWithMultipleReferencesAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							Enums = new
							{
								user.Enum1,
								user.Enum2
							},
							RoleName = user.Role.Name,
							RoleIsActive = (bool?) user.Role.IsActive
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedAnonymousTypeWithComponentReferenceAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							Enums = new
							{
								user.Enum1,
								user.Enum2
							},
							RoleName = user.Role.Name,
							ComponentProperty = user.Component.Property1
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedMemberInitExpressionAsync()
		{
			var query = from user in db.Users
						select new UserDto(user.Id, user.Name)
						{
							InvalidLoginAttempts = user.InvalidLoginAttempts,
							Dto2 = new UserDto2
							{
								RegisteredAt = user.RegisteredAt,
								Enum = user.Enum2
							},
							RoleName = user.Role.Name
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedMemberInitWithinNewExpressionAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							user.InvalidLoginAttempts,
							Dto = new UserDto2
							{
								RegisteredAt = user.RegisteredAt,
								Enum = user.Enum2
							},
							RoleName = user.Role.Name
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectSinglePropertyAsync()
		{
			var query = from user in db.Users
						where user.Name == "ayende"
						select user.RegisteredAt;

			DateTime date = await (query.SingleAsync());
			Assert.AreEqual(new DateTime(2010, 06, 17), date);
		}

		[Test]
		public async Task CanSelectBinaryExpressionsAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							IsSmall = (user.Enum1 == EnumStoredAsString.Small)
						};

			var list = await (query.ToListAsync());

			foreach (var user in list)
			{
				if (user.Name == "rahien")
				{
					Assert.IsTrue(user.IsSmall);
				}
				else
				{
					Assert.IsFalse(user.IsSmall);
				}
			}
		}

		[Test]
		public async Task CanSelectWithMultipleBinaryExpressionsAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							IsAyende = (user.Enum1 == EnumStoredAsString.Medium
								&& user.Enum2 == EnumStoredAsInt32.High)
						};

			var list = await (query.ToListAsync());

			foreach (var user in list)
			{
				if (user.Name == "ayende")
				{
					Assert.IsTrue(user.IsAyende);
				}
				else
				{
					Assert.IsFalse(user.IsAyende);
				}
			}
		}

		[Test]
		public async Task CanSelectWithMultipleBinaryExpressionsWithOrAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							IsAyende = (user.Name == "ayende"
								|| user.Name == "rahien")
						};

			var list = await (query.ToListAsync());

			foreach (var user in list)
			{
				if (user.Name == "ayende" || user.Name == "rahien")
				{
					Assert.IsTrue(user.IsAyende);
				}
				else
				{
					Assert.IsFalse(user.IsAyende);
				}
			}
		}

		[Test]
		public async Task CanSelectWithAnySubQueryAsync()
		{
			var query = from timesheet in db.Timesheets
						select new
						{
							timesheet.Id,
							HasEntries = timesheet.Entries.Any()
						};

			var list = await (query.ToListAsync());

			Assert.AreEqual(2, list.Count(t => t.HasEntries));
			Assert.AreEqual(1, list.Count(t => !t.HasEntries));
		}

		[Test]
		public async Task CanSelectConditionalAsync()
		{
			// SqlServerCeDriver and OdbcDriver have an issue matching the case statements inside select and order by statement,
			// when having one or more parameters inside them. Throws with the following error:
			// ORDER BY items must appear in the select list if SELECT DISTINCT is specified.
			if (!(Sfi.ConnectionProvider.Driver is OdbcDriver) && !(Sfi.ConnectionProvider.Driver is SqlServerCeDriver))
			{
				using (var sqlLog = new SqlLogSpy())
				{
					var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
							   .Select(o => o.ShippedTo.Contains("test") ? o.ShippedTo : o.Customer.CompanyName)
							   .OrderBy(o => o)
							   .Distinct()
							   .ToListAsync());

					Assert.That(FindAllOccurrences(sqlLog.GetWholeLog(), "case"), Is.EqualTo(2));
				}
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						   .Select(o => o.OrderDate.HasValue ? o.OrderDate : o.ShippingDate)
						   .FirstOrDefaultAsync());

				Assert.That(FindAllOccurrences(sqlLog.GetWholeLog(), "case"), Is.EqualTo(1));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						   .Select(o => new
						   {
							   Value = o.OrderDate.HasValue
								   ? o.Customer.CompanyName
								   : (o.ShippingDate.HasValue
									? o.Shipper.CompanyName + "Shipper"
									: o.ShippedTo)
						   })
						   .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
				          .Select(o => new
				          {
					          Value = o.OrderDate.HasValue
						          ? o.Customer.CompanyName
						          : (o.ShippingDate.HasValue
							          ? o.Shipper.CompanyName + "Shipper"
									  : null)
				          })
				          .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						  .Select(o => new
						  {
							  Value = o.OrderDate.HasValue
								  ? o.Customer.CompanyName
								  : (o.ShippingDate.HasValue
									  ? o.Shipper.CompanyName + "Shipper"
									  : "default")
						  })
						  .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}

			var defaultValue = "default";
			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						  .Select(o => new
						  {
							  Value = o.OrderDate.HasValue
								  ? o.Customer.CompanyName
								  : (o.ShippingDate.HasValue
									  ? o.Shipper.CompanyName + "Shipper"
									  : defaultValue)
						  })
						  .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}
		}

		[Test]
		public async Task CanSelectConditionalSubQueryAsync()
		{
			if (!Dialect.SupportsScalarSubSelects)
				Assert.Ignore(Dialect.GetType().Name + " does not support scalar sub-queries");

			var list = await (db.Customers
						   .Select(c => new
						   {
							   Date = db.Orders.Where(o => o.Customer.CustomerId == c.CustomerId)
										.Select(o => o.OrderDate.HasValue ? o.OrderDate : o.ShippingDate)
										.Max()
						   })
						   .ToListAsync());
			Assert.That(list, Has.Count.GreaterThan(0));

			var list2 = await (db.Orders
			              .Select(
				              o => new
				              {
					              UnitPrice = o.Freight.HasValue
						              ? o.OrderLines.Where(l => l.Discount == 1)
						                 .Select(l => l.Product.UnitPrice.HasValue ? l.Product.UnitPrice : l.UnitPrice)
						                 .Max()
						              : o.OrderLines.Where(l => l.Discount == 0)
						                 .Select(l => l.Product.UnitPrice.HasValue ? l.Product.UnitPrice : l.UnitPrice)
						                 .Max()
				              })
			              .ToListAsync());
			Assert.That(list2, Has.Count.GreaterThan(0));

			var list3 = await (db.Orders
						  .Select(o => new
						  {
							  Date = o.OrderLines.Any(l => o.OrderDate.HasValue)
								  ? db.Employees
									  .Select(e => e.BirthDate.HasValue ? e.BirthDate : e.HireDate)
									  .Max()
								  : o.Employee.Superior != null ? o.Employee.Superior.BirthDate : o.Employee.BirthDate
						  })
						  .ToListAsync());
			Assert.That(list3, Has.Count.GreaterThan(0));

			var list4 = await (db.Orders
						  .Select(o => new
						  {
							  Employee = db.Employees.Any(e => e.Superior != null)
								  ? db.Employees
									  .Where(e => e.Superior != null)
									  .Select(e => e.Superior).FirstOrDefault()
								  : o.Employee.Superior != null ? o.Employee.Superior : o.Employee
						  })
						  .ToListAsync());
			Assert.That(list4, Has.Count.GreaterThan(0));
		}

		[Test, KnownBug("NH-3045")]
		public async Task CanSelectFirstElementFromChildCollectionAsync()
		{
			using (var log = new SqlLogSpy())
			{
				var orders = await (db.Customers
					.Select(customer => customer.Orders.OrderByDescending(x => x.OrderDate).First())
					.ToListAsync());

				Assert.That(orders, Has.Count.GreaterThan(0));

				var text = log.GetWholeLog();
				var count = text.Split(new[] { "SELECT" }, StringSplitOptions.None).Length - 1;
				Assert.That(count, Is.EqualTo(1));
			}
		}

		[Test]
		public async Task CanSelectNotMappedEntityPropertyAsync()
		{
			var list = await (db.Animals.Where(o => o.Mother != null).Select(o => o.FatherOrMother.SerialNumber).ToListAsync());

			Assert.That(list, Has.Count.GreaterThan(0));
		}

		[Test]
		public async Task CanProjectWithCastAsync()
		{
			// NH-2463
			// ReSharper disable RedundantCast

			var names1 = await (db.Users.Select(p => new { p1 = p.Name }).ToListAsync());
			Assert.AreEqual(3, names1.Count);

			var names2 = await (db.Users.Select(p => new { p1 = ((User) p).Name }).ToListAsync());
			Assert.AreEqual(3, names2.Count);

			var names3 = await (db.Users.Select(p => new { p1 = (p as User).Name }).ToListAsync());
			Assert.AreEqual(3, names3.Count);

			var names4 = await (db.Users.Select(p => new { p1 = ((IUser) p).Name }).ToListAsync());
			Assert.AreEqual(3, names4.Count);

			var names5 = await (db.Users.Select(p => new { p1 = (p as IUser).Name }).ToListAsync());
			Assert.AreEqual(3, names5.Count);

			var names6 = await (db.Users.Select(p => new { p1 = (long) p.Id }).ToListAsync());
			Assert.AreEqual(3, names6.Count);

			// ReSharper restore RedundantCast
		}

		[Test]
		public async Task CanSelectAfterOrderByAndTakeAsync()
		{
			// NH-3320
			var names = await (db.Users.OrderBy(p => p.Name).Take(3).Select(p => p.Name).ToListAsync());
			Assert.AreEqual(3, names.Count);
		}

		[Test]
		public async Task CanSelectManyWithCastAsync()
		{
			// NH-2688
			// ReSharper disable RedundantCast
			var orders1 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => o.Orders).ToListAsync());
			Assert.AreEqual(5, orders1.Count);

			//$exception	{"c.Orders is not mapped [.SelectMany[NHibernate.DomainModel.Northwind.Entities.Customer,NHibernate.DomainModel.Northwind.Entities.Order](.Where[NHibernate.DomainModel.Northwind.Entities.Customer](NHibernate.Linq.NhQueryable`1[NHibernate.DomainModel.Northwind.Entities.Customer], Quote((c, ) => (String.op_Equality(c.CustomerId, p1))), ), Quote((o, ) => (Convert(o.Orders))), )]"}	System.Exception {NHibernate.Hql.Ast.ANTLR.QuerySyntaxException} 
			// Block OData navigation to detail request requests like 
			// http://localhost:2711/TestWcfDataService.svc/TestEntities(guid&#39;0dd52f6c-1943-4013-a88e-3b63a1fbe11b&#39;)/Details1 
			var orders2 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (ISet<Order>) o.Orders).ToListAsync());
			Assert.AreEqual(5, orders2.Count);

			//$exception	{"([100001].Orders As ISet`1)"}	System.Exception {System.NotSupportedException} 
			var orders3 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (o.Orders as ISet<Order>)).ToListAsync());
			Assert.AreEqual(5, orders3.Count);

			var orders4 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (IEnumerable<Order>) o.Orders).ToListAsync());
			Assert.AreEqual(5, orders4.Count);

			var orders5 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (o.Orders as IEnumerable<Order>)).ToListAsync());
			Assert.AreEqual(5, orders5.Count);
			// ReSharper restore RedundantCast
		}

		[Test]
		public async Task CanSelectCollectionAsync()
		{
			var orders = await (db.Customers.Where(c => c.CustomerId == "VINET").Select(o => o.Orders).ToListAsync());
			Assert.AreEqual(5, orders[0].Count);
		}

		[Test]
		public async Task CanSelectConditionalKnownTypesAsync()
		{
			if (!Dialect.SupportsScalarSubSelects)
				Assert.Ignore(Dialect.GetType().Name + " does not support scalar sub-queries");

			var moreThanTwoOrderLinesBool = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? true : false, Param = true }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesBool.Count(x => x.HasMoreThanTwo == true), Is.EqualTo(410));

			var moreThanTwoOrderLinesNBool = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? true : (bool?)null, Param = (bool?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNBool.Count(x => x.HasMoreThanTwo == true), Is.EqualTo(410));

			var moreThanTwoOrderLinesShort = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? (short)1 : (short)0, Param = (short)0 }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesShort.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesNShort = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? (short?)1 : (short?)null, Param = (short?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNShort.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesInt = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1 : 0, Param = 1 }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesInt.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesNInt = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1 : (int?)null, Param = (int?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNInt.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesDecimal = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1m : 0m, Param = 1m }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesDecimal.Count(x => x.HasMoreThanTwo == 1m), Is.EqualTo(410));

			var moreThanTwoOrderLinesNDecimal = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1m : (decimal?)null, Param = (decimal?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNDecimal.Count(x => x.HasMoreThanTwo == 1m), Is.EqualTo(410));

			var moreThanTwoOrderLinesSingle = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1f : 0f, Param = 1f }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesSingle.Count(x => x.HasMoreThanTwo == 1f), Is.EqualTo(410));

			var moreThanTwoOrderLinesNSingle = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1f : (float?)null, Param = (float?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNSingle.Count(x => x.HasMoreThanTwo == 1f), Is.EqualTo(410));

			var moreThanTwoOrderLinesDouble = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1d : 0d, Param = 1d }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesDouble.Count(x => x.HasMoreThanTwo == 1d), Is.EqualTo(410));

			var moreThanTwoOrderLinesNDouble = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1d : (double?)null, Param = (double?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNDouble.Count(x => x.HasMoreThanTwo == 1d), Is.EqualTo(410));
			
			var moreThanTwoOrderLinesString = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? "yes" : "no", Param = "no" }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesString.Count(x => x.HasMoreThanTwo == "yes"), Is.EqualTo(410));

			var now = DateTime.Now.Date;
			var moreThanTwoOrderLinesDateTime = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.OrderDate.Value : now, Param = now }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesDateTime.Count(x => x.HasMoreThanTwo != now), Is.EqualTo(410));

			var moreThanTwoOrderLinesNDateTime = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.OrderDate : null, Param = (DateTime?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNDateTime.Count(x => x.HasMoreThanTwo != null), Is.EqualTo(410));

			var moreThanTwoOrderLinesGuid = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.Shipper.Reference : Guid.Empty, Param = Guid.Empty }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesGuid.Count(x => x.HasMoreThanTwo != Guid.Empty), Is.EqualTo(410));

			var moreThanTwoOrderLinesNGuid = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.Shipper.Reference : (Guid?)null, Param = (Guid?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNGuid.Count(x => x.HasMoreThanTwo != null), Is.EqualTo(410));
		}

		[Test]
		public async Task CanSelectConditionalEntityAsync()
		{
			var fatherInsteadOfChild = await (db.Animals.Select(a => a.Father.SerialNumber == "5678" ? a.Father : a).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).With.Property("SerialNumber").EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityWithCastAsync()
		{
			var fatherInsteadOfChild = await (db.Mammals.Select(a => a.Father.SerialNumber == "5678" ? (object)a.Father : (object)a).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).With.Property("SerialNumber").EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueAsync()
		{
			var fatherInsteadOfChild = await (db.Animals.Select(a => a.Father.SerialNumber == "5678" ? a.Father.SerialNumber : a.SerialNumber).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityComparisonAsync()
		{
			var father = await (db.Animals.SingleAsync(a => a.SerialNumber == "5678"));
			var fatherInsteadOfChild = await (db.Animals.Select(a => a.Father == father ? a.Father.SerialNumber : a.SerialNumber).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectModulusAsync()
		{
			if (!TestDialect.SendsParameterValuesAsStrings)
			{
				var list = await (db.Animals.Select(a => new { Sql = a.Id % 2.1f, a.Id }).ToListAsync());
				Assert.That(list.Select(o => o.Sql), Is.EqualTo(list.Select(o => o.Id % 2.1f)));
				var list1 = await (db.Animals.Select(a => new { Sql = a.Id % 2.1d, a.Id }).ToListAsync());
				Assert.That(list1.Select(o => o.Sql), Is.EqualTo(list1.Select(o => o.Id % 2.1d)));
				var list2 = await (db.Animals.Select(a => new { Sql = a.BodyWeight % 2.1f, a.BodyWeight }).ToListAsync());
				Assert.That(list2.Select(o => o.Sql), Is.EqualTo(list2.Select(o => o.BodyWeight % 2.1f)));
			}

			var list3 = await (db.Animals.Select(a => new { Sql = a.Id % 2.1m, a.Id }).ToListAsync());
			Assert.That(list3.Select(o => o.Sql), Is.EqualTo(list3.Select(o => o.Id % 2.1m)));
			var list4 = await (db.Animals.Select(a => new { Sql = a.Id % 2, a.Id }).ToListAsync());
			Assert.That(list4.Select(o => o.Sql), Is.EqualTo(list4.Select(o => o.Id % 2)));
			var list5 = await (db.Animals.Select(a => new { Sql = a.Id % 2L, a.Id }).ToListAsync());
			Assert.That(list5.Select(o => o.Sql), Is.EqualTo(list5.Select(o => o.Id % 2L)));
			var list7 = await (db.Animals.Select(a => new { Sql = a.BodyWeight % 2, a.BodyWeight }).ToListAsync());
			Assert.That(list7.Select(o => o.Sql), Is.EqualTo(list7.Select(o => o.BodyWeight % 2)));
			var list8 = await (db.Animals.Select(a => new { Sql = a.BodyWeight % 2L, a.BodyWeight }).ToListAsync());
			Assert.That(list8.Select(o => o.Sql), Is.EqualTo(list8.Select(o => o.BodyWeight % 2L)));
			var list9 = await (db.Products.Select(a => new { Sql = a.UnitPrice % 2L, a.UnitPrice }).ToListAsync());
			Assert.That(list9.Select(o => o.Sql), Is.EqualTo(list9.Select(o => o.UnitPrice % 2L)));
			var list10 = await (db.Products.Select(a => new { Sql = a.UnitPrice % 2, a.UnitPrice }).ToListAsync());
			Assert.That(list10.Select(o => o.Sql), Is.EqualTo(list10.Select(o => o.UnitPrice % 2)));
		}

		[Test]
		public async Task CanSelectModulusSameExpressionAsync()
		{
			var list1 = await (db.Animals.Select(a => new ObjectDto { CalculatedValue = a.Id % 2.1m, OriginalValue = a.Id }).ToListAsync());
			Assert.That(list1.Select(o => o.CalculatedValue), Is.EqualTo(list1.Select(o => o.OriginalValue % 2.1m)));
			var list2 = await (db.Animals.Select(a => new ObjectDto { CalculatedValue = a.Id % 2L, OriginalValue = a.Id }).ToListAsync());
			Assert.That(list2.Select(o => o.CalculatedValue), Is.EqualTo(list2.Select(o => o.OriginalValue % 2L)));

			if (!TestDialect.SendsParameterValuesAsStrings)
			{
				var list3 = await (db.Animals.Select(a => new ObjectDto { CalculatedValue = a.Id % 2.1f, OriginalValue = a.Id }).ToListAsync());
				Assert.That(list3.Select(o => o.CalculatedValue), Is.EqualTo(list3.Select(o => o.OriginalValue % 2.1f)));
				var list4 = await (db.Animals.Select(a => new ObjectDto { CalculatedValue = a.Id % 2.1d, OriginalValue = a.Id }).ToListAsync());
				Assert.That(list4.Select(o => o.CalculatedValue), Is.EqualTo(list4.Select(o => o.OriginalValue % 2.1d)));
			}
		}

		[Test]
		public async Task CanForceClientEvaluationAsync()
		{
			var query = db.Animals.Select(a => ClientEval(() => a.Id + 5));
			Assert.That(GetSqlSelect(query), Does.Not.Contain("+"));
			Assert.That(await (query.ToListAsync()), Is.EqualTo(await (db.Animals.Select(a => a.Id + 5).ToListAsync())));

			query = db.Animals.Select(a => ClientEval(() => a.SerialNumber.Length));
			Assert.That(GetSqlSelect(query), Does.Not.Contain("len(").And.Not.Contain("length("));
			Assert.That(await (query.ToListAsync()), Is.EqualTo(await (db.Animals.Select(a => a.SerialNumber.Length).ToListAsync())));

			var query2 = db.Animals.Select(a => ClientEval(() => a.SerialNumber.Substring(0, 1)));
			Assert.That(GetSqlSelect(query2), Does.Not.Contain("substr(").And.Not.Contain("substring("));
			Assert.That(await (query2.ToListAsync()), Is.EqualTo(await (db.Animals.Select(a => a.SerialNumber.Substring(0, 1)).ToListAsync())));

			query2 = db.Animals.Select(a => ClientEval(() => a.Id % 2 == 0 ? a.SerialNumber : a.Description));
			Assert.That(GetSqlSelect(query2), Does.Not.Contain("case"));
			Assert.That(await (query2.ToListAsync()), Is.EqualTo(await (db.Animals.Select(a => a.Id % 2 == 0 ? a.SerialNumber : a.Description).ToListAsync())));

			var query3 = await (db.Animals.Select(a => new
			{
				Client = ClientEval(() => a.Id % 2 == 0 ? a.SerialNumber.Substring(0, 1) : a.Description),
				Server = a.Id % 2 == 0 ? a.SerialNumber.Substring(0, 1) : a.Description,
			}).ToListAsync());
			Assert.That(query3.Select(o => o.Client), Is.EqualTo(query3.Select(o => o.Server)));
		}

		[Test]
		public async Task CanSelectMultiplyOperatorAsync()
		{
			if (TestDialect.SendsParameterValuesAsStrings)
			{
				Assert.Ignore("Ignore due to driver double and float parameters issue");
			}

			var list1 = await (db.Animals.Select(a => new { Sql = a.Id * 5, a.Id }).ToListAsync());
			Assert.That(list1.Select(o => o.Sql), Is.EqualTo(list1.Select(o => o.Id * 5)));
			var list2 = await (db.Animals.Select(a => new { Sql = a.Id * 12345.54321m, a.Id }).ToListAsync());
			Assert.That(list2.Select(o => o.Sql), Is.EqualTo(list2.Select(o => o.Id * 12345.54321m)));
			var list3 = await (db.Animals.Select(a => new { Sql = a.Id * 12345.54321f, a.Id }).ToListAsync());
			Assert.That(list3.Select(o => o.Sql), Is.EqualTo(list3.Select(o => o.Id * 12345.54321f)));
			var list4 = await (db.Animals.Select(a => new { Sql = a.Id * 12345.54321d, a.Id }).ToListAsync());
			Assert.That(list4.Select(o => o.Sql), Is.EqualTo(list4.Select(o => o.Id * 12345.54321d)));
			var list5 = await (db.Animals.Select(a => new { Sql = a.Id * 2L, a.Id }).ToListAsync());
			Assert.That(list5.Select(o => o.Sql), Is.EqualTo(list5.Select(o => o.Id * 2L)));

			var list6 = await (db.Products.Select(a => new { Sql = a.UnitPrice * 12345.54321m, a.UnitPrice }).ToListAsync());
			Assert.That(list6.Select(o => o.Sql), Is.EqualTo(list6.Select(o => o.UnitPrice * 12345.54321m)));
			var list7 = await (db.Products.Select(a => new { Sql = a.UnitPrice * 12345L, a.UnitPrice }).ToListAsync());
			Assert.That(list7.Select(o => o.Sql), Is.EqualTo(list7.Select(o => o.UnitPrice * 12345L)));

			var list8 = await (db.Animals.Select(a => new { Sql = a.BodyWeight * 12345.54321f, a.BodyWeight }).ToListAsync());
			Assert.That(list8.Select(o => o.Sql), Is.EqualTo(list8.Select(o => o.BodyWeight * 12345.54321f)));
		}

		[Test]
		public async Task CanSelectDivideOperatorAsync()
		{
			if (TestDialect.SendsParameterValuesAsStrings)
			{
				Assert.Ignore("Ignore due to driver double and float parameters issue");
			}

			var list1 = await (db.Animals.Select(a => new { Sql = a.Id / 5, a.Id }).ToListAsync());
			Assert.That(list1.Select(o => o.Sql), Is.EqualTo(list1.Select(o => o.Id / 5)));
			var list2 = await (db.Animals.Select(a => new { Sql = a.Id / 12345.54321m, a.Id }).ToListAsync());
			Assert.That(list2.Select(o => o.Sql), Is.EqualTo(list2.Select(o => o.Id / 12345.54321m)));
			var list3 = await (db.Animals.Select(a => new { Sql = a.Id / 12345.54321f, a.Id }).ToListAsync());
			Assert.That(list3.Select(o => o.Sql), Is.EqualTo(list3.Select(o => o.Id / 12345.54321f)));
			var list4 = await (db.Animals.Select(a => new { Sql = a.Id / 12345.54321d, a.Id }).ToListAsync());
			Assert.That(list4.Select(o => o.Sql), Is.EqualTo(list4.Select(o => o.Id / 12345.54321d)));
			var list5 = await (db.Animals.Select(a => new { Sql = a.Id / 2L, a.Id }).ToListAsync());
			Assert.That(list5.Select(o => o.Sql), Is.EqualTo(list5.Select(o => o.Id / 2L)));

			var list6 = await (db.Products.Select(a => new { Sql = a.UnitPrice / 12345.54321m, a.UnitPrice }).ToListAsync());
			Assert.That(list6.Select(o => o.Sql), Is.EqualTo(list6.Select(o => o.UnitPrice / 12345.54321m)));
			var list7 = await (db.Products.Select(a => new { Sql = a.UnitPrice.Value / 12345L, a.UnitPrice }).ToListAsync());
			Assert.That(list7.Select(o => o.Sql), Is.EqualTo(list7.Select(o => o.UnitPrice / 12345L)));

			var list8 = await (db.Animals.Select(a => new { Sql = a.BodyWeight / 12345.54321f, a.BodyWeight }).ToListAsync());
			Assert.That(list8.Select(o => o.Sql), Is.EqualTo(list8.Select(o => o.BodyWeight / 12345.54321f)));
		}

		[Test]
		public async Task CanSelectAddOperatorAsync()
		{
			var list1 = await (db.Animals.Select(a => new { Sql = a.Id + 5, a.Id }).ToListAsync());
			Assert.That(list1.Select(o => o.Sql), Is.EqualTo(list1.Select(o => o.Id + 5)));
			var list2 = await (db.Animals.Select(a => new { Sql = a.Id + 12345.54321m, a.Id }).ToListAsync());
			Assert.That(list2.Select(o => o.Sql), Is.EqualTo(list2.Select(o => o.Id + 12345.54321m)));
			var list3 = await (db.Animals.Select(a => new { Sql = a.Id + 12345.54321f, a.Id }).ToListAsync());
			Assert.That(list3.Select(o => o.Sql), Is.EqualTo(list3.Select(o => o.Id + 12345.54321f)));
			var list4 = await (db.Animals.Select(a => new { Sql = a.Id + 12345.54321d, a.Id }).ToListAsync());
			Assert.That(list4.Select(o => o.Sql), Is.EqualTo(list4.Select(o => o.Id + 12345.54321d)));
			var list5 = await (db.Animals.Select(a => new { Sql = a.Id + 2L, a.Id }).ToListAsync());
			Assert.That(list5.Select(o => o.Sql), Is.EqualTo(list5.Select(o => o.Id + 2L)));

			var list6 = await (db.Products.Select(a => new { Sql = a.UnitPrice + 12345.54321m, a.UnitPrice }).ToListAsync());
			Assert.That(list6.Select(o => o.Sql), Is.EqualTo(list6.Select(o => o.UnitPrice + 12345.54321m)));
			var list7 = await (db.Products.Select(a => new { Sql = a.UnitPrice + 12345L, a.UnitPrice }).ToListAsync());
			Assert.That(list7.Select(o => o.Sql), Is.EqualTo(list7.Select(o => o.UnitPrice + 12345L)));

			var list8 = await (db.Animals.Select(a => new { Sql = a.BodyWeight + 12345.54321f, a.BodyWeight }).ToListAsync());
			Assert.That(list8.Select(o => o.Sql), Is.EqualTo(list8.Select(o => o.BodyWeight + 12345.54321f)));
		}

		[Test]
		public async Task CanSelectSubtractOperatorAsync()
		{
			var list1 = await (db.Animals.Select(a => new { Sql = a.Id - 5, a.Id }).ToListAsync());
			Assert.That(list1.Select(o => o.Sql), Is.EqualTo(list1.Select(o => o.Id - 5)));
			var list2 = await (db.Animals.Select(a => new { Sql = a.Id - 12345.54321m, a.Id }).ToListAsync());
			Assert.That(list2.Select(o => o.Sql), Is.EqualTo(list2.Select(o => o.Id - 12345.54321m)));
			var list3 = await (db.Animals.Select(a => new { Sql = a.Id - 12345.54321f, a.Id }).ToListAsync());
			Assert.That(list3.Select(o => o.Sql), Is.EqualTo(list3.Select(o => o.Id - 12345.54321f)));
			var list4 = await (db.Animals.Select(a => new { Sql = a.Id - 12345.54321d, a.Id }).ToListAsync());
			Assert.That(list4.Select(o => o.Sql), Is.EqualTo(list4.Select(o => o.Id - 12345.54321d)));
			var list5 = await (db.Animals.Select(a => new { Sql = a.Id - 2L, a.Id }).ToListAsync());
			Assert.That(list5.Select(o => o.Sql), Is.EqualTo(list5.Select(o => o.Id - 2L)));

			var list6 = await (db.Products.Select(a => new { Sql = a.UnitPrice - 12345.54321m, a.UnitPrice }).ToListAsync());
			Assert.That(list6.Select(o => o.Sql), Is.EqualTo(list6.Select(o => o.UnitPrice - 12345.54321m)));
			var list7 = await (db.Products.Select(a => new { Sql = a.UnitPrice - 12345L, a.UnitPrice }).ToListAsync());
			Assert.That(list7.Select(o => o.Sql), Is.EqualTo(list7.Select(o => o.UnitPrice - 12345L)));

			var list8 = await (db.Animals.Select(a => new { Sql = a.BodyWeight - 12345.54321f, a.BodyWeight }).ToListAsync());
			Assert.That(list8.Select(o => o.Sql), Is.EqualTo(list8.Select(o => o.BodyWeight - 12345.54321f)));
		}

		private class ObjectDto
		{
			public object CalculatedValue { get; set; }

			public int OriginalValue { get; set; }
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityComparisonComplexAsync()
		{
			var animal = await (db.Animals.Select(
				               a => new
				               {
								   Parent = a.Father != null || a.Mother != null ? (a.Father ?? a.Mother) : null,
								   ParentSerialNumber = a.Father != null || a.Mother != null ? (a.Father ?? a.Mother).SerialNumber : null,
								   Parent2 = a.Mother ?? a.Father,
								   a.Father,
								   a.Mother
				               })
			               .FirstOrDefaultAsync(o => o.ParentSerialNumber == "5678"));

			Assert.That(animal, Is.Not.Null);
			Assert.That(animal.Father, Is.Not.Null);
			Assert.That(animal.Mother, Is.Not.Null);
			Assert.That(animal.Parent, Is.Not.Null);
			Assert.That(animal.Parent2, Is.Not.Null);
			Assert.That(NHibernateUtil.IsInitialized(animal.Parent), Is.True);
			Assert.That(NHibernateUtil.IsInitialized(animal.Parent2), Is.True);
			Assert.That(NHibernateUtil.IsInitialized(animal.Father), Is.True);
			Assert.That(NHibernateUtil.IsInitialized(animal.Mother), Is.True);
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityCastAsync()
		{
			var list = await (db.Animals.Select(
							   a => new
							   {
								   BodyWeight = (double?) (a is Cat
									   ? (a.Father ?? a.Mother).BodyWeight
										: (a is Dog
											? (a.Mother ?? a.Father).BodyWeight
											: (a.Father.Father.BodyWeight)
									   ))
							   })
						   .ToListAsync());
			Assert.That(list, Has.Exactly(1).With.Property("BodyWeight").Not.Null);
		}

		[Test]
		public async Task CanSelectBinaryClientSideTestAsync()
		{
			var exception = Assert.ThrowsAsync<GenericADOException>(() =>
			{
				return db.Animals.Select(a => a.FatherOrMother.BodyWeight + a.BodyWeight).ToListAsync();
			});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Double'. Cast expression '([a].FatherOrMother.BodyWeight + [a].BodyWeight)' to 'System.Nullable`1[System.Double]'."));

			var list = await (db.Animals.Select(a => (double?) (a.FatherOrMother.BodyWeight + a.BodyWeight)).ToListAsync());
			Assert.That(list, Has.Exactly(5).Null.And.Exactly(1).EqualTo(271d));

			// Arithmetic operator
			var list2 = await (db.Animals.Select(a => new
			{
				// Left side null
				Client = (double?) (a.FatherOrMother.BodyWeight + a.BodyWeight + a.Father.BodyWeight),
				Server = (double?) (a.Father ?? a.Mother).BodyWeight + a.BodyWeight + a.Father.BodyWeight,
				// Right side null
				Client2 = (double?) (a.BodyWeight - a.Father.BodyWeight - a.FatherOrMother.BodyWeight),
				Server2 = (double?) a.BodyWeight - a.Father.BodyWeight - (a.Father ?? a.Mother).BodyWeight
			}).ToListAsync());
			Assert.That(list2.Select(o => o.Client), Is.EqualTo(list2.Select(o => o.Server)));
			Assert.That(list2.Select(o => o.Client2), Is.EqualTo(list2.Select(o => o.Server2)));

			// Boolean logic operator
			var list3 = await (db.Users.Select(u => new
			{
				// Left side null
				Client = u.NotMappedUser.Role.IsActive && true,
				Server = u.Role.IsActive && true,
				// Right side null
				Client2 = true && u.NotMappedUser.Role.IsActive,
				Server2 = true && u.Role.IsActive
			}).ToListAsync());
			Assert.That(list3.Select(o => o.Client), Is.EqualTo(list3.Select(o => o.Server)));
			Assert.That(list3.Select(o => o.Client2), Is.EqualTo(list3.Select(o => o.Server2)));

			list3 = await (db.Users.Select(u => new
			{
				// Left side null
				Client = u.NotMappedUser.Role.IsActive || true,
				Server = u.Role.IsActive || true,
				// Right side null
				Client2 = false || u.NotMappedUser.Role.IsActive,
				Server2 = false || u.Role.IsActive
			}).ToListAsync());
			Assert.That(list3.Select(o => o.Client), Is.EqualTo(list3.Select(o => o.Server)));
			Assert.That(list3.Select(o => o.Client2), Is.EqualTo(list3.Select(o => o.Server2)));

			// Comparison operator
			list3 = await (db.Users.Select(u => new
			{
				// Left side null
				Client = u.NotMappedUser.Role.Id > 0,
				Server = u.Role.Id > 0,
				// Right side null
				Client2 = 0 < u.NotMappedUser.Role.Id,
				Server2 = 0 < u.Role.Id
			}).ToListAsync());
			Assert.That(list3.Select(o => o.Client), Is.EqualTo(list3.Select(o => o.Server)));
			Assert.That(list3.Select(o => o.Client2), Is.EqualTo(list3.Select(o => o.Server2)));

			// Bitwise boolean operator
			var list4 = await (db.Users.Select(u => new
			{
				// Left side null
				Client = (bool?) (u.NotMappedUser.Role.IsActive | true),
				Server = (bool?) (u.Role.IsActive | true),
				// Right side null
				Client2 = (bool?) (true | u.NotMappedUser.Role.IsActive),
				Server2 = (bool?) (true | u.Role.IsActive)
			}).ToListAsync());
			Assert.That(list4.Select(o => o.Client), Is.EqualTo(list4.Select(o => o.Server)));
			Assert.That(list4.Select(o => o.Client2), Is.EqualTo(list4.Select(o => o.Server2)));

			// Bitwise number operator
			var list5 = await (db.Users.Select(u => new
			{
				// Left side null
				Client = (int?) (u.NotMappedUser.Role.Id | 5),
				Server = (int?) (u.Role.Id | 5),
				// Right side null
				Client2 = (int?) (5 | u.NotMappedUser.Role.Id),
				Server2 = (int?) (5 | u.Role.Id)
			}).ToListAsync());
			Assert.That(list5.Select(o => o.Client), Is.EqualTo(list5.Select(o => o.Server)));
			Assert.That(list5.Select(o => o.Client2), Is.EqualTo(list5.Select(o => o.Server2)));

			// Coalesce operator
			var list6 = await (db.Users.Select(u => new
			{
				// Left side null
				Client = u.NotMappedUser.Role.Name ?? u.NotMappedUser.Name,
				Server = u.Role.Name ?? u.Name,
				// Right side null
				Client2 = u.NotMappedUser.Name ?? u.NotMappedUser.Role.Name,
				Server2 = u.Name ?? u.Role.Name,
				// Both side null
				Client3 = u.NotMappedUser.Role.Name ?? u.NotMappedUser.Role.Name,
				Server3 = u.Role.Name ?? u.Role.Name
			}).ToListAsync());
			Assert.That(list6.Select(o => o.Client), Is.EqualTo(list6.Select(o => o.Server)));
			Assert.That(list6.Select(o => o.Client2), Is.EqualTo(list6.Select(o => o.Server2)));
			Assert.That(list6.Select(o => o.Client3), Is.EqualTo(list6.Select(o => o.Server3)));
		}

		[Test]
		public async Task CanSelectUnaryClientSideTestAsync()
		{
			var exception = Assert.ThrowsAsync<GenericADOException>(() =>
			{
				return db.Animals.Select(a => -a.FatherOrMother.BodyWeight).ToListAsync();
			});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Double'. Cast expression '-[a].FatherOrMother.BodyWeight' to 'System.Nullable`1[System.Double]'."));

			// Negate
			var list = await (db.Animals.Select(a => new
			{
				Client = (double?) -a.FatherOrMother.BodyWeight,
				Server = (double?) -((a.Father ?? a.Mother).BodyWeight)
			}).ToListAsync());
			Assert.That(list.Select(o => o.Client), Is.EqualTo(list.Select(o => o.Server)));

			// Convert
			list = await (db.Animals.Select(a => new
			{
				Client = (double?) a.FatherOrMother.BodyWeight,
				Server = (double?) (a.Father ?? a.Mother).BodyWeight
			}).ToListAsync());
			Assert.That(list.Select(o => o.Client), Is.EqualTo(list.Select(o => o.Server)));

			// UnaryPlus
			list = await (db.Animals.Select(a => new
			{
				Client = (double?) +a.FatherOrMother.BodyWeight,
				Server = (double?) +((a.Father ?? a.Mother).BodyWeight)
			}).ToListAsync());
			Assert.That(list.Select(o => o.Client), Is.EqualTo(list.Select(o => o.Server)));

			// Not
			var list2 = await (db.Users.Select(u => new
			{
				Client = (bool?) !u.NotMappedUser.Role.IsActive,
				Server = (bool?) !u.Role.IsActive
			}).ToListAsync());
			Assert.That(list2.Select(o => o.Client), Is.EqualTo(list2.Select(o => o.Server)));

			// Convert value type
			var list3 = await (db.Users.Select(u => (int?) (u.Role != null ? 5 : 10)).ToListAsync());
			Assert.That(list3, Has.Exactly(3).Not.Null);

			// Convert enum
			list3 = await (db.Users.Select(u => (int?) u.Role.CreatedBy.Enum2).ToListAsync());
			Assert.That(list3, Has.Exactly(3).Null);

			// Convert reference type
			var list4 = await (db.Animals.Select(a => new
			{ 
				Client = (Dog) a.FatherOrMother,
				Server = (Dog) (a.Father ?? a.Mother)
			}).ToListAsync());
			Assert.That(list4.Select(o => o.Client), Is.EqualTo(list4.Select(o => o.Server)));

			// TypeAs
			list4 = await (db.Animals.Select(a => new
			{
				Client = a.FatherOrMother as Dog,
				Server = (a.Father ?? a.Mother) as Dog
			}).ToListAsync());
			Assert.That(list4.Select(o => o.Client), Is.EqualTo(list4.Select(o => o.Server)));

			// Convert constant reference type
			var list5 = await (db.Animals.Select(a => (Animal) new Dog()).ToListAsync());
			Assert.That(list5, Has.Exactly(6).Not.Null);
		}

		[Test]
		public async Task CanSelectConditionalClientSideWithNullValueTypeTestAsync()
		{
			var exception = Assert.ThrowsAsync<GenericADOException>(() =>
			{
				return db.Animals.Select(
							   a => new
							   {
								   BodyWeight = (string.IsNullOrWhiteSpace(a.Description)
										? a.Mother.Mother.BodyWeight
										: a.Father.Mother.BodyWeight)
							   })
						   .ToListAsync();
			});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Double'. " +
				"Cast expression 'IIF(IsNullOrWhiteSpace([a].Description), [_3].BodyWeight, [_1].BodyWeight)' to 'System.Nullable`1[System.Double]'."));

			var list = await (db.Animals.Select(
							   a => new
							   {
								   BodyWeight = (double?) (string.IsNullOrWhiteSpace(a.Description)
										? a.Mother.Mother.BodyWeight
										: a.Father.Mother.BodyWeight)
							   })
						   .ToListAsync());
			Assert.That(list, Has.Exactly(0).With.Property("BodyWeight").Not.Null);

			var list2 = await (db.Animals.Select(
							   a => new
							   {
								   BodyWeight = (double?) (string.IsNullOrWhiteSpace(a.Description)
										? a.Mother.Mother.BodyWeight
										: 5d)
							   })
						   .ToListAsync());
			Assert.That(list2, Has.Exactly(0).With.Property("BodyWeight").Not.Null);

			var list3 = await (db.Animals.Select(
							   a => new
							   {
								   BodyWeight = (double?) (string.IsNullOrWhiteSpace(a.Description)
										? 5d
										: a.Father.Mother.BodyWeight)
							   })
						   .ToListAsync());
			Assert.That(list3, Has.Exactly(6).With.Property("BodyWeight").Not.Null);

			var list4 = await (db.Animals.Select(
							   a => new
							   {
								   BodyWeightHashCode = (int?) ((string.IsNullOrWhiteSpace(a.Description)
										? a.Mother.Mother.BodyWeight
										: a.Father.Mother.BodyWeight)).GetHashCode()
							   })
						   .ToListAsync());
			Assert.That(list4, Has.Exactly(0).With.Property("BodyWeightHashCode").Not.Null);

			var list5 = await (db.Animals.Select(
							   a => new
							   {
								   BodyWeight = (double?) (string.IsNullOrWhiteSpace(a.Description)
										? (string.IsNullOrWhiteSpace(a.Description)
											? a.Mother.Mother.BodyWeight
											: a.Father.Mother.BodyWeight)
										: (string.IsNullOrWhiteSpace(a.Description)
											? a.Mother.Mother.BodyWeight
											: a.Father.Mother.BodyWeight))
							   })
						   .ToListAsync());
			Assert.That(list5, Has.Exactly(0).With.Property("BodyWeight").Not.Null);

			var list6 = await (db.Animals.Select(
							   a => new
							   {
								   Client =  a.Father.HasFather ? (double?) null : a.BodyWeight,
								   Server = a.Father.Father != null ? (double?) null : a.BodyWeight,
							   })
						   .ToListAsync());
			Assert.That(list6.Select(o => o.Client), Is.EqualTo(list6.Select(o => o.Server)));

			var list7 = await (db.Users.Select(
							   a => new
							   {
								   Client = a.NotMappedUser.Role.IsActive ? 1 : 2,
								   Server = a.Role.IsActive ? 1 : 2
							   })
						   .ToListAsync());
			Assert.That(list7.Select(o => o.Client), Is.EqualTo(list7.Select(o => o.Server)));
		}

		[Test]
		public async Task CanExecuteMethodWithNullObjectClientSideTestAsync()
		{
			var exception = Assert.ThrowsAsync<GenericADOException>(() =>
			{
				return db.Animals.Select(
							  a => new
							  {
								  a.Id,
								  FatherId = a.Father.Father.Id
							  })
						  .ToListAsync();
			});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Int32'. Cast expression '[_0].Father.Id' to 'System.Nullable`1[System.Int32]'."));

			exception = Assert.ThrowsAsync<GenericADOException>(() =>
			{
				return db.Animals.Select(
							  a => new
							  {
								  a.Id,
								  FatherIdHashCode = a.Father.Father.Id.GetHashCode()
							  })
						  .ToListAsync();
			});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Int32'. Cast expression '[_1].Id.GetHashCode()' to 'System.Nullable`1[System.Int32]'."));

			var list = await (db.Animals.Select(
							   a => new
							   {
								   NullableId = (int?) a.Father.Father.Id,
								   NullableIdHashCode = (int?) a.Father.Father.Id.GetHashCode()
							   })
						   .ToListAsync());
			Assert.That(list, Has.Exactly(0).With.Property("NullableId").Not.Null);
		}

		[Test]
		public void CanSelectWithIsOperatorAsync()
		{
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => a is Dog).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => a.FatherSerialNumber is string).ToListAsync());
		}

		[Test]
		public async Task CanSelectNonMappedComponentPropertyAsync()
		{
			Assert.DoesNotThrowAsync(() => db.Users.Select(u => u.Component.Property3).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Users.Select(u => u.Component.OtherComponent.OtherProperty2).ToListAsync());
			var list = await (db.Users.Select(u => new
			{
				u.Component.OtherComponent.OtherProperty1,
				OtherProperty3 = u.Component.OtherComponent.OtherProperty2,
				u.Component.Property1,
				u.Component.Property2,
				u.Component.Property3
			}).ToListAsync());
			Assert.That(list.Select(o => o.OtherProperty3), Is.EqualTo(list.Select(o => o.OtherProperty1)));
			Assert.That(
				list.Select(o => (o.Property1 ?? o.Property2) == null ? null : $"{o.Property1}{o.Property2}"),
				Is.EqualTo(list.Select(o => o.Property3)));
		}

		[Test]
		public void CanSelectWithAnInvocationAsync()
		{
			Func<string, string> func = s => s + "postfix";
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => func(a.SerialNumber)).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => func(a.FatherSerialNumber)).ToListAsync());
		}

		[Test]
		public void CanSelectEnumerableAsync()
		{
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.Id } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.Id, 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a, a.Father, a.Mother } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new
			{
				Enumerable = new[]
				{
					new UserDto(a.Id, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber},
					new UserDto(1, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber, InvalidLoginAttempts = 1},
					null,
					new UserDto(1, "test") {RoleName = "test", InvalidLoginAttempts = 1},
					new UserDto(1, "test") {Dto2List = {new UserDto2(), new UserDto2()}, Dto2 = {Enum = EnumStoredAsInt32.High}},
					new UserDto(1, a.FatherSerialNumber)
					{
						Dto2List = {new UserDto2() { Enum = a.Id > 0 ? EnumStoredAsInt32.High : EnumStoredAsInt32.Unspecified }, new UserDto2()},
						Dto2 = {Enum = a.Id > 0 ? EnumStoredAsInt32.High : EnumStoredAsInt32.Unspecified}
					}
				}
			}).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.SerialNumber, a.FatherSerialNumber, null } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new int[][] { new[] { a.Id }, new[] { 1 }, new[] { a.Id, 1 } } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<int> { a.Id, 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<int>(5) { a.Id, 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<int>(a.Id) { 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<string>(a.Id) { a.SerialNumber, a.FatherSerialNumber, null } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new
			{
				Enumerable = new List<UserDto>(a.Id)
				{
					new UserDto(a.Id, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber},
					new UserDto(1, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber, InvalidLoginAttempts = 1},
					null,
					new UserDto(1, "test") {RoleName = "test", InvalidLoginAttempts = 1},
					new UserDto(1, "test") {Dto2List = {new UserDto2(), new UserDto2()}, Dto2 = {Enum = EnumStoredAsInt32.High}},
					new UserDto(1, a.FatherSerialNumber)
					{
						Dto2List = {new UserDto2() { Enum = a.Id > 0 ? EnumStoredAsInt32.High : EnumStoredAsInt32.Unspecified }, new UserDto2()},
						Dto2 = {Enum = a.Id > 0 ? EnumStoredAsInt32.High : EnumStoredAsInt32.Unspecified}
					}
				}
			}).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.SerialNumber, a.FatherSerialNumber, null }[a.Id - a.Id].Length }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<string> { a.SerialNumber, a.FatherSerialNumber, null }[a.Id - a.Id].Length }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new
			{
				Enumerable = new Dictionary<string, string>
			{
				{ a.SerialNumber, a.FatherSerialNumber },
				{ "1", a.Father.SerialNumber },
				{ "2", null }
			}[a.SerialNumber]
			}).ToListAsync());
		}

		[Test]
		public async Task CanSelectConditionalSubClassPropertyValueAsync()
		{
			var animal = await (db.Animals.Select(
				               a => new
				               {
					               Pregnant = a is Mammal ? ((Mammal) a).Pregnant : false
				               })
			               .Where(o => o.Pregnant)
			               .ToListAsync());

			Assert.That(animal, Has.Count.EqualTo(1));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityComparisonRepeatAsync()
		{
			// Check again in the same ISessionFactory to ensure caching doesn't cause failures
			await (CanSelectConditionalEntityValueWithEntityComparisonAsync());
		}

		[Test]
		public async Task CanSelectConditionalObjectAsync()
		{
			var fatherIsKnown = await (db.Animals.Select(a => new { a.SerialNumber, Superior = a.Father.SerialNumber, FatherIsKnown = a.Father.SerialNumber == "5678" ? (object)true : (object)false }).ToListAsync());
			Assert.That(fatherIsKnown, Has.Exactly(1).With.Property("FatherIsKnown").True);
		}

		[Test]
		public async Task CanCastToDerivedTypeAsync()
		{
			var dogs = await (db.Animals
			                      .Where(a => ((Dog) a).Pregnant)
			                      .Select(a => new {a.SerialNumber})
			                      .ToListAsync());
			Assert.That(dogs, Has.Exactly(1).With.Property("SerialNumber").Not.Null);
		}

		[Test]
		public async Task CanCastToCustomRegisteredTypeAsync()
		{
			TypeFactory.RegisterType(typeof(NullableInt32), new NullableInt32Type(), Enumerable.Empty<string>());
			Assert.That(await (db.Users.Where(o => (NullableInt32) o.Id == 1).ToListAsync()), Has.Count.EqualTo(1));
		}

		[Test]
		public async Task TestClientSideEvaluationAsync()
		{
			var list = await (db.Animals.Select(a => new
			{
				ClientSide = string.IsNullOrEmpty(a.FatherSerialNumber) ? 1 : 0,
				ClientSide2 = string.IsNullOrEmpty(a.Father.SerialNumber) ? 1 : 0
			}).ToListAsync());
			Assert.That(list.Select(o => o.ClientSide), Is.EqualTo(list.Select(o => o.ClientSide2)));

			var list2 = await (db.Animals.Select(a => new
			{
				ClientSide = a.Father.IsProxy(),
				ClientSide2 = a.FatherSerialNumber.IsProxy()
			}).ToListAsync());
			Assert.That(list2.Select(o => o.ClientSide), Is.EqualTo(list2.Select(o => o.ClientSide2)));

			var list3 = await (db.Orders.Where(o => o.OrderDate.HasValue).Select(o => new
			{
				ClientSide = o.OrderDate.Value.TimeOfDay.Days,
				ClientSide2 = o.OrderDate.Value
			}).ToListAsync());
			Assert.That(list3.Select(o => o.ClientSide), Is.EqualTo(list3.Select(o => o.ClientSide2.TimeOfDay.Days)));

			var list4 = await (db.Orders.Where(o => o.OrderDate.HasValue).Select(o => new
			{
				o.OrderId,
				ClientSide = o.OrderDate.Value.TimeOfDay.CompareTo(new TimeSpan(o.OrderId)),
				ClientSide2 = o.OrderDate.Value
			}).ToListAsync());
			Assert.That(list4.Select(o => o.ClientSide), Is.EqualTo(list4.Select(o => o.ClientSide2.TimeOfDay.CompareTo(new TimeSpan(o.OrderId)))));
		}

		[Test]
		public async Task TestServerAndClientSideEvaluationComparisonAsync()
		{
			var list = await (db.Animals.Select(
				a => new
				{
					ServerSide = (int?) a.Father.SerialNumber.Length,
					ClientSide = (int?) a.FatherSerialNumber.Length
				}).ToListAsync());
			Assert.That(list.Select(o => o.ClientSide), Is.EqualTo(list.Select(o => o.ServerSide)));

			var list1 = await (db.Animals
						 .Where(a => a.Father.SerialNumber != null)
						 .Select(
							 a => new
							 {
								 ServerSide = a.Father.SerialNumber.Length,
								 ClientSide = a.FatherSerialNumber.Length
							 })
						 .ToListAsync());
			Assert.That(list1.Select(o => o.ClientSide), Is.EqualTo(list1.Select(o => o.ServerSide)));

			var clientSide = await (db.Animals.Select(a => a.FatherSerialNumber.Length.ToString()).ToListAsync());
			var serverSide = await (db.Animals.Select(a => a.FatherSerialNumber.Length.ToString()).ToListAsync());
			Assert.That(clientSide, Is.EqualTo(serverSide));

			var exception = Assert.ThrowsAsync<GenericADOException>(
				() =>
				{
					return db.Animals.Select(
						a => new
						{
							ServerSide = a.Father.SerialNumber.Length
						}).ToListAsync();
				});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Int32'. Cast expression '[_0].SerialNumber.Length' to 'System.Nullable`1[System.Int32]'."));

			exception = Assert.ThrowsAsync<GenericADOException>(
				() =>
				{
					return db.Animals.Select(
						a => new
						{
							ClientSide = a.FatherSerialNumber.Length
						}).ToListAsync();
				});
			Assert.That(exception.InnerException, Is.TypeOf<InvalidOperationException>());
			Assert.That(exception.InnerException.Message, Is.EqualTo(
				"Null value cannot be assigned to a value type 'System.Int32'. Cast expression '[a].FatherSerialNumber.Length' to 'System.Nullable`1[System.Int32]'."));

			var list2 = await (db.Animals.Select(
				a => new
				{
					ServerSide = a.Father.SerialNumber.Length.ToString(),
					ClientSide = a.FatherSerialNumber.Length.ToString()
				}).ToListAsync());
			Assert.That(list2.Select(o => o.ClientSide), Is.EqualTo(list2.Select(o => o.ServerSide)));

			var list3 = await (db.Animals.Select(
				a => new
				{
					ServerSide = (int?) a.Father.SerialNumber.Substring(0, ((int?) a.Father.SerialNumber.Length - 1) ?? 0).Length,
					ClientSide = (int?) a.FatherSerialNumber.Substring(0, ((int?) a.FatherSerialNumber.Length - 1) ?? 0).Length
				}).ToListAsync());
			Assert.That(list3.Select(o => o.ClientSide), Is.EqualTo(list3.Select(o => o.ServerSide)));

			var list4 = await (db.Animals.Select(a => new
			{
				ServerSide = a.Father.SerialNumber,
				ClientSide = a.FatherSerialNumber,
				Test = (object) null
			}).ToListAsync());
			Assert.That(list4.Select(o => o.ClientSide), Is.EqualTo(list4.Select(o => o.ServerSide)));

			var list5 = await (db.Animals.Select(a => new
			{
				ServerSide = a.Father.SerialNumber == null,
				ClientSide = a.FatherSerialNumber == null
			}).ToListAsync());
			Assert.That(list5.Select(o => o.ClientSide), Is.EqualTo(list5.Select(o => o.ServerSide)));

			var list6 = await (db.Animals
						  .Where(a => a.Father.SerialNumber != null)
						  .Select(
							  a => new
							  {
								  ServerSide = -a.Father.SerialNumber.Length,
								  ClientSide = -a.FatherSerialNumber.Length
							  }).ToListAsync());
			Assert.That(list6.Select(o => o.ClientSide), Is.EqualTo(list6.Select(o => o.ServerSide)));

			var list7 = await (db.Animals
						  .Select(
							  a => new
							  {
								  ServerSide = a.Father != null ? a.Father.SerialNumber : null,
								  ClientSide = a.HasFather ? a.FatherSerialNumber : null
							  }).ToListAsync());
			Assert.That(list7.Select(o => o.ClientSide), Is.EqualTo(list7.Select(o => o.ServerSide)));

			var list8 = await (db.Animals
			              .Where(a => a is Dog)
			              .Select(
				              a => new
				              {
					              ServerSide = (long?) (int?) ((Dog) a).Father.SerialNumber.Length,
					              ClientSide = (long?) (int?) ((Dog) a).FatherSerialNumber.Length
				              }).ToListAsync());
			Assert.That(list8.Select(o => o.ClientSide), Is.EqualTo(list8.Select(o => o.ServerSide)));
		}

		public class Wrapper<T>
		{
			public T item;
			public string message;
		}

		private static void AssertOneSelectColumn(IQueryable query)
		{
			using (var sqlLog = new SqlLogSpy())
			{
				// Execute query
				foreach (var item in query) { }
				Assert.That(FindAllOccurrences(sqlLog.GetWholeLog(), "as col"), Is.EqualTo(1));
			}
		}

		private static string GetSqlSelect(IQueryable query)
		{
			using (var sqlLog = new SqlLogSpy())
			{
				// Execute query
				foreach (var item in query) { }

				var sql = sqlLog.GetWholeLog();
				return sql.Substring(0, sql.IndexOf(" from"));
			}
		}

		private static int FindAllOccurrences(string source, string substring)
		{
			if (source == null)
			{
				return 0;
			}
			int n = 0, count = 0;
			while ((n = source.IndexOf(substring, n, StringComparison.InvariantCulture)) != -1)
			{
				n += substring.Length;
				++count;
			}
			return count;
		}
	}
}
