//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH1343
{
	using System.Threading.Tasks;
	[TestFixture]
	public class ProductFixtureAsync : BugTestCase
	{
		protected override void OnTearDown()
		{
			using (ISession session = OpenSession())
			{
				session.Delete("from OrderLine");
				session.Delete("from Product");
				session.Flush();
			}
		}

		[Test]
		public async Task ProductQueryPassesParsingButFailsAsync()
		{
			Product product1 = new Product("product1");
			OrderLine orderLine = new OrderLine("1", product1);
			
			using (ISession session = OpenSession())
			{
				await (session.SaveAsync(product1));
				await (session.SaveAsync(orderLine));
				await (session.FlushAsync());

				IQuery query = session.GetNamedQuery("GetLinesForProduct");
				query.SetParameter("product", product1);
				IList<OrderLine> list = await (query.ListAsync<OrderLine>());
				Assert.AreEqual(1, list.Count);
			}
		}

		[Test]
		public async Task ProductQueryPassesAndExecutesRightIfPuttingAliasAsync()
		{
			Product product1 = new Product("product1");
			OrderLine orderLine = new OrderLine("1", product1);

			using (ISession session = OpenSession())
			{
				await (session.SaveAsync(product1));
				await (session.SaveAsync(orderLine));
				await (session.FlushAsync());

				IQuery query = session.GetNamedQuery("GetLinesForProductWithAlias");
				query.SetParameter("product", product1);
				IList<OrderLine> list = await (query.ListAsync<OrderLine>());
				Assert.AreEqual(1, list.Count);
			}
		}
	}
}