//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v1.1.4322
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace NHibernate.DomainModel
{

 /// <summary>
 /// POJO for B
 /// </summary>
 /// <remark>
 /// This class is autogenerated
 /// </remark>
 [Serializable]
 public class B : A
 {

	#region Fields
	/// <summary>
	/// Holder for count
	/// </summary>
	private Int32 _count;
	
	/// <summary>
	/// Holder for map
	/// </summary>
	private System.Collections.IDictionary _map;
	
	#endregion

	#region Constructors
	/// <summary>
	/// Default constructor for class B
	/// </summary>
	public B()
	{
	}
	
	/// <summary>
	/// Constructor for class B
	/// </summary>
	/// <param name="name">Initial name value</param>
	/// <param name="count">Initial count value</param>
	/// <param name="map">Initial map value</param>
	public B(String name, Int32 count, System.Collections.IDictionary map)
		: base(name)
	{
		this._count = count;
		this._map = map;
	}
	
	/// <summary>
	/// Minimal constructor for class B
	/// </summary>
	/// <param name="map">Initial map value</param>
	public B(System.Collections.IDictionary map)
	{
		this._map = map;
	}
	#endregion
	
	#region Properties
	/// <summary>
	/// Get/set for count
	/// </summary>
	public Int32 Count
	{
		get
		{
			return this._count;
		}
		set
		{
			this._count = value;
		}
	}
	
	/// <summary>
	/// Get/set for map
	/// </summary>
	public System.Collections.IDictionary Map
	{
		get
		{
			return this._map;
		}
		set
		{
			this._map = value;
		}
	}
	
	#endregion
 }
}