//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using System.Linq;
using NHibernate.Cache;
using NHibernate.Cfg;
using NHibernate.Impl;
using NHibernate.Test.SecondLevelCacheTests;
using NSubstitute;
using NUnit.Framework;

namespace NHibernate.Test.SecondLevelCacheTest
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class InvalidationTestsAsync : TestCase
	{
		protected override string MappingsAssembly => "NHibernate.Test";

		protected override IList Mappings => new[] { "SecondLevelCacheTest.Item.hbm.xml" };

		protected override void Configure(Configuration configuration)
		{
			base.Configure(configuration);
			configuration.Properties[Environment.CacheProvider] = typeof(HashtableCacheProvider).AssemblyQualifiedName;
			configuration.Properties[Environment.UseQueryCache] = "true";
		}

		[Test]
		public async Task InvalidatesEntitiesAsync()
		{
			var cache = Substitute.For<UpdateTimestampsCache>(Sfi.Settings, new Dictionary<string, string>());
			((SessionFactoryImpl) (Sfi as DebugSessionFactory).ActualFactory).SetPropertyUsingReflection(
				x => x.UpdateTimestampsCache,
				cache);

			//"Received" assertions can not be used since the collection is reused and cleared between calls.
			//The received args are cloned and stored
			var preInvalidations = new List<IReadOnlyCollection<string>>();
			var invalidations = new List<IReadOnlyCollection<string>>();

			cache
				.When(x=>x.PreInvalidate(Arg.Any<IReadOnlyCollection<string>>()))
				.Do(x=>preInvalidations.Add(((IReadOnlyCollection<string>) x[0]).ToList()));
			cache
				.When(x => x.Invalidate(Arg.Any<IReadOnlyCollection<string>>()))
				.Do(x => invalidations.Add(((IReadOnlyCollection<string>) x[0]).ToList()));

			using (ISession session = OpenSession())
			{
				using (ITransaction tx = session.BeginTransaction())
				{
					foreach (var i in Enumerable.Range(1, 10))
					{
						var item = new Item {Id = i};
						await (session.SaveAsync(item));
					}

					await (tx.CommitAsync());
				}

				using (ITransaction tx = session.BeginTransaction())
				{
					foreach (var i in Enumerable.Range(1, 10))
					{
						var item = await (session.GetAsync<Item>(i));
						item.Name = item.Id.ToString();
					}

					await (tx.CommitAsync());
				}

				using (ITransaction tx = session.BeginTransaction())
				{
					foreach (var i in Enumerable.Range(1, 10))
					{
						var item = await (session.GetAsync<Item>(i));
						await (session.DeleteAsync(item));
					}

					await (tx.CommitAsync());
				}
			}

			//Should receive one preinvalidation and one invalidation per commit
			Assert.That(preInvalidations.Count,Is.EqualTo(3));
			Assert.That(preInvalidations.All(x => x.Count == 1 && x.First() == "Item"), Is.True);

			Assert.That(invalidations.Count, Is.EqualTo(3));
			Assert.That(invalidations.All(x => x.Count == 1 && x.First() == "Item"), Is.True);

		}

		private bool IsRight(HashSet<string> x)
		{
			return x.Count == 1 && x.First() == "Item";
		}

		public async Task CleanUpAsync(CancellationToken cancellationToken = default(CancellationToken))
		{
			using (ISession s = OpenSession())
			using (ITransaction tx = s.BeginTransaction())
			{
				await (s.DeleteAsync("from Item", cancellationToken));
				await (tx.CommitAsync(cancellationToken));
			}
		}

		public void CleanUp()
		{
			using (ISession s = OpenSession())
			using (ITransaction tx = s.BeginTransaction())
			{
				s.Delete("from Item");
				tx.Commit();
			}
		}

		protected override void OnTearDown()
		{
			CleanUp();
			base.OnTearDown();
		}
	}
}
