//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NHibernate.Event
{
	using System.Threading.Tasks;
	using System.Threading;
	/// <content>
	/// Contains generated async methods
	/// </content>
	public partial interface IDirtyCheckEventListener
	{
		/// <summary>Handle the given dirty-check event. </summary>
		/// <param name="event">The dirty-check event to be handled. </param>
		/// <param name="cancellationToken">A cancellation token that can be used to cancel the work</param>
		Task OnDirtyCheckAsync(DirtyCheckEvent @event, CancellationToken cancellationToken);
	}
}