//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NUnit.Framework;

namespace NHibernate.Test.Join
{
	using System.Threading.Tasks;
	[TestFixture]
	public class NH1059FixtureAsync : TestCase
	{
		protected override string MappingsAssembly
		{
			get { return "NHibernate.Test"; }
		}

		protected override IList Mappings
		{
			get
			{
				return new string[] { 
					"Join.Worker.hbm.xml",
				};
			}
		}

		protected override void OnTearDown()
		{
			using (ISession s = OpenSession())
			using (ITransaction tx = s.BeginTransaction())
			{
				s.Delete("from Worker");

				tx.Commit();
			}
		}

		[Test]
		public async Task FetchJoin_ForNH1059Async()
		{
			using (ISession s = OpenSession())
			using (ITransaction tx = s.BeginTransaction())
			{
				// This line would fail before the fix
				await (s.CreateQuery("from Worker").ListAsync<Worker>());
			}
		}

		[Test]
		public async Task FetchJoinWithCriteria_ForNH1059Async()
		{
			using (ISession s = OpenSession())
			using (ITransaction tx = s.BeginTransaction())
			{
				// This line would fail before the fix
				await (s.CreateCriteria(typeof(Worker)).ListAsync<Worker>());
			}
		}
	}
}
