//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Data;
using NHibernate.Cfg.MappingSchema;
using NHibernate.Dialect;
using NHibernate.Mapping.ByCode;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH4004
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : TestCaseMappingByCode
	{
		protected override bool AppliesTo(Dialect.Dialect dialect)
		{
			return dialect is MsSql2012Dialect;
		}

		protected override HbmMapping GetMappings()
		{
			var mapper = new ModelMapper();
			mapper.Class<Entity>(
				rc =>
				{
					rc.Id(
						x => x.Id,
						m => m.Generator(
							Generators.Sequence,
							gm => gm.Params(
								new
								{
									sequence = "`entity_seq`"
								}
							)));
					rc.Property(x => x.Name);
				});

			return mapper.CompileMappingForAllExplicitlyAddedEntities();
		}

		protected override bool CheckDatabaseWasCleaned()
		{
			//NO OP
			return true;
		}

		[Test]
		public async Task SequenceShallBeDroppedAsync()
		{
			DropSchema();

			using (var connection = await (Sfi.ConnectionProvider.GetConnectionAsync(CancellationToken.None)))
			{
				var command = connection.CreateCommand();
				command.CommandText = "SELECT COUNT(*) FROM sys.sequences WHERE NAME = 'entity_seq'";
				command.CommandType = CommandType.Text;
				var count = (int) await (command.ExecuteScalarAsync());

				Assert.That(count, Is.EqualTo(0));
			}
		}
	}
}
