//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Linq;
using NHibernate.Linq;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH3392
{
    using System.Threading.Tasks;
    [TestFixture]
    public class FixtureAsync : BugTestCase
	{
        protected override void OnTearDown()
        {
            using (ISession session = OpenSession())
            using (ITransaction transaction = session.BeginTransaction())
            {
                session.Delete("from Kid");
                session.Delete("from FriendOfTheFamily");
                session.Delete("from Dad");
                session.Delete("from Mum");
                session.Flush();
                transaction.Commit();
            }
        }

        [Test]
        public async Task ExpandSubCollectionWithEmbeddedCompositeIDAsync()
        {
            using (ISession s = OpenSession())
            using (var tx = s.BeginTransaction())
            {

	            var jenny = new Mum {Name = "Jenny"};
	            await (s.SaveAsync(jenny));
	            var benny = new Dad {Name = "Benny"};
	            await (s.SaveAsync(benny));
	            var lenny = new Dad {Name = "Lenny"};
	            await (s.SaveAsync(lenny));
	            var jimmy = new Kid {Name = "Jimmy", MumId = jenny.Id, DadId = benny.Id};
	            await (s.SaveAsync(jimmy));
	            var timmy = new Kid {Name = "Timmy", MumId = jenny.Id, DadId = lenny.Id};
	            await (s.SaveAsync(timmy));

	            await (tx.CommitAsync());
            }

	        using (var s = OpenSession())
            {
                var result=await (s.Query<Mum>().Select(x => new { x, x.Kids }).ToListAsync());
                Assert.That(result.Count, Is.EqualTo(1));
                Assert.That(result[0].x.Kids, Is.EquivalentTo(result[0].Kids));
            }
        }

        [Test]
        public async Task ExpandSubCollectionWithCompositeIDAsync()
        {
            using (ISession s = OpenSession())
			using (var tx = s.BeginTransaction())
            {

                var jenny = new Mum { Name = "Jenny" };
                await (s.SaveAsync(jenny));
                var benny = new Dad { Name = "Benny" };
                await (s.SaveAsync(benny));
                var lenny = new Dad { Name = "Lenny" };
                await (s.SaveAsync(lenny));
                var jimmy = new FriendOfTheFamily { Name = "Jimmy", Id = new MumAndDadId { MumId = jenny.Id, DadId = benny.Id } };
                await (s.SaveAsync(jimmy));
                var timmy = new FriendOfTheFamily { Name = "Timmy", Id = new MumAndDadId { MumId = jenny.Id, DadId = lenny.Id } };
                await (s.SaveAsync(timmy));

                await (tx.CommitAsync());
            }

            using (var s = OpenSession())
            {
                var result=await (s.Query<Mum>().Select(x => new { x, x.Friends }).ToListAsync());
                Assert.That(result.Count, Is.EqualTo(1));
                Assert.That(result[0].x.Friends, Is.EquivalentTo(result[0].Friends));
            }
        }

		
	}
}
