//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Linq;
using System.Text.RegularExpressions;
using NHibernate.Cfg.MappingSchema;
using NHibernate.Linq;
using NHibernate.Mapping.ByCode;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH2505
{
	using System.Threading.Tasks;

	[TestFixture]
	public class FixtureAsync: TestCaseMappingByCode
	{
		private Regex caseClause = new Regex("case",RegexOptions.IgnoreCase);
		protected override HbmMapping GetMappings()
		{
			var mapper = new ConventionModelMapper();
			mapper.BeforeMapClass += (mi, t, x) => x.Id(map=> map.Generator(Generators.Guid));
			return mapper.CompileMappingFor(new[] { typeof(MyClass) });
		}

		private class Scenario: IDisposable
		{
			private readonly ISessionFactory factory;

			public Scenario(ISessionFactory factory)
			{
				this.factory = factory;
				using (var session= factory.OpenSession())
				{
					session.Save(new MyClass { Alive = true });
					session.Save(new MyClass { Alive = false, MayBeAlive = true });
					session.Save(new MyClass { Alive = false, MayBeAlive = false });
					session.Flush();
				}
			}

			public void Dispose()
			{
				using (var session = factory.OpenSession())
				{
					session.CreateQuery("delete from MyClass").ExecuteUpdate();
					session.Flush();
				}
			}
		}

		[Test]
		public async Task WhenQueryConstantEqualToMemberThenDoNotUseCaseStatementAsync()
		{
			using (new Scenario(Sfi))
			{
				using (var session = OpenSession())
				{
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => x.Alive == false).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(2));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => true == x.Alive).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(1));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
				}
			}
		}

		[Test]
		public async Task WhenQueryConstantNotEqualToMemberThenDoNotUseCaseStatementAsync()
		{
			using (new Scenario(Sfi))
			{
				using (var session = OpenSession())
				{
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => x.Alive != false).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(1));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => true != x.Alive).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(2));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
				}
			}
		}

		[Test]
		public async Task WhenQueryComplexEqualToComplexThentUseTheCaseStatementForBothAsync()
		{
			using (new Scenario(Sfi))
			{
				using (var session = OpenSession())
				{
					using (var sqls = new SqlLogSpy())
					{
						await (session.Query<MyClass>().Where(x => (5 > x.Something) == (x.Something < 10)).ToListAsync());
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(2));
					}
				}
			}
		}

		[Test]
		public async Task WhenQueryConstantEqualToNullableMemberThenDoNotUseCaseStatementAsync()
		{
			using (new Scenario(Sfi))
			{
				using (var session = OpenSession())
				{
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => x.MayBeAlive == false).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(1));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => true == x.MayBeAlive).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(1));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
				}
			}
		}

		[Test]
		public async Task WhenQueryConstantEqualToNullableMemberValueThenDoNotUseCaseStatementAsync()
		{
			using (new Scenario(Sfi))
			{
				using (var session = OpenSession())
				{
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => x.MayBeAlive.Value == false).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(1));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => true == x.MayBeAlive.Value).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(1));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
				}
			}
		}

		[Test]
		public async Task WhenQueryConstantNotEqualToNullableMemberThenDoNotUseCaseStatementAsync()
		{
			using (new Scenario(Sfi))
			{
				using (var session = OpenSession())
				{
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => x.MayBeAlive != false).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(2));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
					using (var sqls = new SqlLogSpy())
					{
						var list = await (session.Query<MyClass>().Where(x => true != x.MayBeAlive).ToListAsync());
						Assert.That(list, Has.Count.EqualTo(2));
						Assert.That(caseClause.Matches(sqls.GetWholeLog()).Count, Is.EqualTo(0));
					}
				}
			}
		}
	}
}
