//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Linq;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH3221
{
	using System.Threading.Tasks;
	[TestFixture]
	public class WeirdBehaviourAsync : BugTestCase
	{
		private Guid nicePersonId;

		[Test]
		public async Task CanAddATodoAsync()
		{
			using (ISession session = OpenSession())
			{
				var person = new Person("myName");
				person.AddTodo(new Todo(person) { Name = "I need to get it" });
				await (session.SaveAsync(person));
				nicePersonId = person.Id;
				Assert.AreEqual(1, person.Todos.Count());
				await (session.FlushAsync());
			}
			using (ISession session = OpenSession())
			{
				var person = await (session.GetAsync<Person>(nicePersonId));
				Assert.AreEqual(1, person.Todos.Count());
				Assert.AreEqual(person.Todos.ToList()[0].Person.Id, person.Id);
			}
		}

		[Test]
		public async Task CanRemoveATodoAsync()
		{
			Todo myTodo;
			using (ISession session = OpenSession())
			{
				var person = new Person("myName2");                
				myTodo = person.AddTodo(new Todo(person) { Name = "I need to get it" });
				await (session.SaveAsync(person));
				nicePersonId = person.Id;
				Assert.AreEqual(1, person.Todos.Count());
				await (session.FlushAsync());
			}

			using (ISession session = OpenSession())
			{
				var person = await (session.GetAsync<Person>(nicePersonId));
				Assert.AreEqual(1, person.Todos.Count());
				person.RemoveTodo(myTodo);
				Assert.AreEqual(0, person.Todos.Count());
				await (session.FlushAsync());
			}

			using (ISession session = OpenSession())
			{
				var person = await (session.GetAsync<Person>(nicePersonId));
				Assert.AreEqual(0, person.Todos.Count());
			}
		}

		[Test]
		public async Task CanAddStuffAsync()
		{
			using (ISession session = OpenSession())
			{
				var person = new Person("myName3");
				person.AddStuff(new Stuff(person) { Name = "this pen is mine" });
				await (session.SaveAsync(person));
				nicePersonId = person.Id;
				Assert.AreEqual(1, person.MyStuff.Count());
				await (session.FlushAsync());
			}

			using (ISession session = OpenSession())
			{
				var person = await (session.GetAsync<Person>(nicePersonId));
				Assert.AreEqual(1, person.MyStuff.Count());
				Assert.AreEqual(person.MyStuff.ToList()[0].Person.Id, person.Id);
			}
		}

		[Test]
		public async Task CanRemoveStuffAsync()
		{
			Stuff myStuff;
			using (ISession session = OpenSession())
			{
				var person = new Person("MyName4");
				myStuff = person.AddStuff(new Stuff(person) { Name = "BallPen" });
				await (session.SaveAsync(person));
				nicePersonId = person.Id;
				Assert.AreEqual(1, person.MyStuff.Count());
				await (session.FlushAsync());
			}

			using (ISession session = OpenSession())
			{
				var person = await (session.GetAsync<Person>(nicePersonId));
				Assert.AreEqual(1, person.MyStuff.Count());
				person.RemoveStuff(myStuff);
				Assert.AreEqual(0, person.MyStuff.Count());
				await (session.FlushAsync());
			}

			using (ISession session = OpenSession())
			{
				var person = await (session.GetAsync<Person>(nicePersonId));
				Assert.AreEqual(0, person.MyStuff.Count());
			}
		}

		protected override void OnSetUp()
		{
			base.OnSetUp();
			Console.WriteLine("=====================BEGIN TEST");
		}

		protected override void OnTearDown()
		{
			Console.WriteLine("=====================END TEST");
			base.OnTearDown();
			using (ISession session = OpenSession())
			{
				const string hql = "from System.Object";
				session.Delete(hql);
				session.Flush();
			}
		}
	}
}