using NHibernate.Id;
using NHibernate.SqlCommand;

namespace NHibernate.Dialect
{
	/// <summary>
	/// A dialect for Firebird 3 and above.
	/// </summary>
	/// <remarks>
	/// Firebird 3 supports the SQL standard <c>OFFSET</c>/<c>FETCH</c> clause. Unlike the
	/// <c>FIRST</c>/<c>SKIP</c> clause used by <see cref="FirebirdDialect" />, it is placed at the end of
	/// the statement and applies to the whole query, including unions.
	/// </remarks>
	public class Firebird3Dialect : FirebirdDialect
	{
		public override SqlString GetLimitString(SqlString queryString, SqlString offset, SqlString limit)
		{
			var result = new SqlStringBuilder(queryString);

			if (offset != null)
			{
				result.Add(" offset ").Add(offset).Add(" rows");
			}

			if (limit != null)
			{
				result.Add(" fetch first ").Add(limit).Add(" rows only");
			}

			return result.ToSqlString();
		}

		/// <inheritdoc />
		public override bool SupportsIdentityColumns => true;

		/// <inheritdoc />
		public override string IdentityColumnString => "generated by default as identity";

		/// <inheritdoc />
		public override bool SupportsInsertSelectIdentity => true;

		/// <inheritdoc />
		public override SqlString AppendIdentitySelectToInsert(SqlString insertString, string identifierColumnName)
		{
			return insertString.Append(" returning ", identifierColumnName);
		}

		/// <inheritdoc />
		public override string NoColumnsInsertString => "default values";

		/// <inheritdoc />
		/// <remarks>
		/// The native generator keeps using sequences.
		/// </remarks>
		public override System.Type NativeIdentifierGeneratorClass => typeof(SequenceGenerator);

		#region Sequence support

		/// <inheritdoc />
		public override bool SupportsPooledSequences => true;

		/// <inheritdoc />
		public override string GetCreateSequenceString(string sequenceName)
		{
			return "create sequence " + sequenceName;
		}

		/// <inheritdoc />
		public override string GetDropSequenceString(string sequenceName)
		{
			return "drop sequence " + sequenceName;
		}

		/// <inheritdoc />
		public override string GetSequenceNextValString(string sequenceName)
		{
			return "select " + GetSelectSequenceNextValString(sequenceName) + " from RDB$DATABASE";
		}

		/// <inheritdoc />
		public override string GetSelectSequenceNextValString(string sequenceName)
		{
			return "next value for " + sequenceName;
		}

		#endregion
	}
}
