using NHibernate.Id;
using NHibernate.SqlCommand;

namespace NHibernate.Dialect
{
	/// <summary>
	/// A dialect specifically for use with Oracle 12c.
	/// </summary>
	/// <remarks>
	/// The main differences between this dialect and <see cref="Oracle10gDialect"/>
	/// are the use of the "offset/fetch" pagination syntax and the support of identity columns.
	/// </remarks>
	public class Oracle12cDialect : Oracle10gDialect
	{
		/// <summary>
		/// Oracle 12c supports a query statement that provides <c>LIMIT</c>
		/// functionality with an offset.
		/// </summary>
		/// <value><c>false</c></value>
		public override bool UseMaxForLimit
		{
			get { return false; }
		}

		public override SqlString GetLimitString(SqlString querySqlString, SqlString offset, SqlString limit)
		{
			var result = new SqlStringBuilder(querySqlString);

			if (offset != null)
			{
				result.Add(" OFFSET ");
				result.Add(offset).Add(" ROWS");
			}

			if (limit != null)
			{
				result.Add(" FETCH FIRST ").Add(limit).Add(" ROWS ONLY");
			}

			return result.ToSqlString();
		}

		// 128 since 12.2. https://stackoverflow.com/a/756569/1178314, will
		// have to do a 12-2c dialect for exploiting it, or wait for 13.
		// / <inheritdoc />
		//public override int MaxAliasLength => 128;

		/// <inheritdoc />
		public override bool SupportsIdentityColumns => true;

		/// <inheritdoc />
		/// <remarks>Oracle has no "select last identity value" statement, see
		/// <see cref="Oracle8iDialect.AddIdentifierOutParameterToInsert" />.</remarks>
		public override bool SupportsIdentifierOutParameter => true;

		/// <inheritdoc />
		/// <remarks><c>by default on null</c> rather than <c>always</c>, for allowing explicit identifier
		/// values as the other dialects supporting identity columns do.</remarks>
		public override string IdentityColumnString => "generated by default on null as identity";

		/// <inheritdoc />
		/// <remarks>Oracle does not support an insert without any column.</remarks>
		public override string IdentityInsertString => "default";

		/// <inheritdoc />
		/// <remarks>Oracle keeps sequences as its native generator: using identity columns has to stay an
		/// explicit choice, for not breaking existing schemas.</remarks>
		public override System.Type NativeIdentifierGeneratorClass => typeof(SequenceGenerator);
	}
}
