//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Cfg.MappingSchema;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH2977
{
	using System.Threading.Tasks;
	/// <summary>
	/// Fixture using 'by code' mappings
	/// </summary>
	/// <remarks>
	/// This fixture is identical to <see cref="Fixture" /> except the <see cref="Entity" /> mapping is performed 
	/// by code in the GetMappings method, and does not require the <c>Mappings.hbm.xml</c> file. Use this approach
	/// if you prefer.
	/// </remarks>
	[TestFixture]
	public class ByCodeFixtureAsync : TestCaseMappingByCode
	{
		protected override HbmMapping GetMappings()
		{
			return new HbmMapping();
		}

		protected override bool AppliesTo(Dialect.Dialect dialect)
		{
			return dialect is Dialect.MsSql2000Dialect;
		}

		[Test]
		public async Task CanGetUniqueStoredProcedureResultAsync()
		{
			using (ISession session = OpenSession())
			using (session.BeginTransaction())
			{
				var result = await (session.CreateSQLQuery("EXEC sp_stored_procedures ?")
					.SetString(0, "sp_help")
					.UniqueResultAsync());
				Assert.That(result, Is.Not.Null);
			}
		}

		[Test]
		public async Task CanLimitStoredProcedureResultsAsync()
		{
			using (ISession session = OpenSession())
			using (session.BeginTransaction())
			{
				var result = await (session.CreateSQLQuery("EXEC sp_stored_procedures")
					.SetMaxResults(5)
					.ListAsync());
				Assert.That(result, Has.Count.EqualTo(5));
			}
		}
	}
}
