//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Cfg.MappingSchema;
using NHibernate.Mapping.ByCode;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH941
{
	using System.Threading.Tasks;
	[TestFixture]
	public class FixtureAsync : TestCaseMappingByCode
	{
		protected override HbmMapping GetMappings()
		{
			var mapper = new ModelMapper();
			mapper.Class<MyClass>(rc =>
			                      {
			                      	rc.Id(x => x.Id, map => map.Generator(Generators.HighLow));
			                      	rc.Bag(x => x.Relateds, map =>
			                      	                        {
																												map.Key(km => km.NotNullable(true));
			                      	                        	map.Cascade(Mapping.ByCode.Cascade.All);
			                      	                        }, rel => rel.OneToMany());
			                      });
			mapper.Class<Related>(rc => rc.Id(x => x.Id, map => map.Generator(Generators.HighLow)));
			HbmMapping mappings = mapper.CompileMappingForAllExplicitlyAddedEntities();
			return mappings;
		}

		[Test]
		public async Task WhenSaveOneThenShouldSaveManyAsync()
		{
			using (ISession session = OpenSession())
			{
				using (ITransaction tx = session.BeginTransaction())
				{
					var one = new MyClass();
					one.Relateds = new List<Related> {new Related(), new Related()};
					await (session.PersistAsync(one));
					await (tx.CommitAsync());
				}
			}
			using (ISession session = OpenSession())
			{
				using (ITransaction tx = session.BeginTransaction())
				{
					await (session.CreateQuery("delete from Related").ExecuteUpdateAsync());
					await (session.CreateQuery("delete from MyClass").ExecuteUpdateAsync());
					await (tx.CommitAsync());
				}
			}
		}
	}
}
