//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Linq;
using NUnit.Framework;
using NHibernate.Linq;

namespace NHibernate.Test.NHSpecificTest.GH1313
{
	using System.Threading.Tasks;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		protected override void OnSetUp()
		{
			using var session = OpenSession();
			using var transaction = session.BeginTransaction();

			var account = new Account { Id = 1, Name = "Account_1", OldAccountNumber = 1 };
			var order = new HoldClose
			{
				Account = account,
				CloseDate = new DateTime(2023, 1, 1)
			};

			session.Save(account);
			session.Save(order);
			transaction.Commit();
		}

		protected override void OnTearDown()
		{
			using var session = OpenSession();
			using var transaction = session.BeginTransaction();

			session.CreateQuery("delete from System.Object").ExecuteUpdate();
			transaction.Commit();
		}

		[Test]
		[Explicit("Not fixed yet")]
		public async Task ManyToOneTargettingAFormulaAsync()
		{
			using var session = OpenSession();
			using var transaction = session.BeginTransaction();

			var result = session.Query<HoldClose>();

			Assert.That(await (result.ToListAsync()), Has.Count.EqualTo(1));
			await (transaction.CommitAsync());
		}
	}
}
