//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Transactions;
using NHibernate.DomainModel;
using NUnit.Framework;

namespace NHibernate.Test.SystemTransactions
{
	using System.Threading.Tasks;
	[TestFixture]
	public class TransactionFixtureAsync : TestCase
	{
		protected override IList Mappings
		{
			get { return new string[] { "WZ.hbm.xml" }; }
		}

		[Test]
		public async Task CanUseSystemTransactionsToCommitAsync()
		{
			object identifier;
			using(ISession session = Sfi.OpenSession())
			using(TransactionScope tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
			{
				W s = new W();
				await (session.SaveAsync(s));
				identifier = s.Id;
				tx.Complete();
			}

			using (ISession session = Sfi.OpenSession())
			using (TransactionScope tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
			{
				W w = await (session.GetAsync<W>(identifier));
				Assert.IsNotNull(w);
				await (session.DeleteAsync(w));
				tx.Complete();
			}
		}
	}
}